require('../bower_components/angular/angular.js')
require("../bower_components/angular-aria/angular-aria.js")
require("../bower_components/angular-animate/angular-animate.js")
require("../bower_components/angular-material/angular-material.js")
window.d3 = require('../bower_components/d3/d3.js')
window._ = require('../bower_components/lodash/dist/lodash.js')
require('./ngApp.js')
require('./classes.js')
require('./fileService.js')
require('./sunburst.js')
require('./mainController.js')
